### ISSUE TITLE
Add nullability annotations for non-null by default migration

### ISSUE THREAD

**Issue by cbracken** [google/quiver-dart#606]
In preparation for [NNBD](https://github.com/dart-lang/language/issues/110) in Dart, we'll need to add nullability annotations throughout Quiver.

Steps:
* [x] Apply migration tool hiniting to all libraries/tests with no cross-dependencies on other quiver libraries. This allows us to maximise our use to the `dart migrate` tool, since (as far as I can tell), it's not possible to run it over a partially migrated package.
* [x] Add language version annotation of `// @dart 2.9` to remaining files
* [x] Land migration of all hinted files; update infra to set `--enable-experiment=non-nullable`.
* [x] Migrate remaining libraries one at a time, removing language version annotations.

Libraries to migrate:
* [x] async/collect (no change necessary)
* [x] async/concat (#644)
* [x] async/countdown_timer (#656)
* [x] async/enumerate (no change necessary)
* [x] async/future_stream (#657)
* [x] async/iteration (#658)
* [x] async/metronome (#661)
* [x] async/stream_buffer (#659)
* [x] async/stream_router (#660)
* [x] async/string (no change necessary)
* [x] cache (#654)
* [x] check (#638)
* [x] collection/bimap (#650)
* [x] collection/delegates (#641)
* [x] collection/lrumap (#651)
* [x] collection/multimap (#655)
* [x] collection/treeset (#662)
* [x] collection/utils (#649)
* [x] core (#633, #652)
* [x] iterables (#643)
* [x] pattern (#639)
* [x] strings (#640)
* [x] time (no change necessary)
* [x] testing/async (#642)
* [x] testing/equality (#642)
* [x] testing/time (#642)

**Comment by rokob** [comment]
I'd like to help out here if I can because I'd like core to get marked as non-nullable so that tuple can get migrated so that I can then migrate some of my libraries that depend on those two. If I understand correctly, you can still be backwards compatible with pre-NNBD SDKs even if you opt-in a file with the new SDK annotation, but you just don't get all the benefits until everyone opts-in. So why not just incrementally opt-in files rather than committing all of the comments?

**Comment by cbracken** [comment]
@rokob Sorry for the delay -- I missed your comment earlier. I've updated the steps above in an effort to clarify the rationale for checking in the hinted files for as long as possible. It comes down to maximising our use of the migration tool which, as far as I can tell, doesn't support running on partially-migrated packages, nor does it support running on a single library at a time within a package.

Given that most packages are significantly smaller than quiver, it's probably much less of a problem than it is here.

**Comment by cbracken** [comment]
At this point patches are out for all sub-libraries. Once Multimap and TreeSet are migrated, I'll attempt to roll this internally and we'll see how cleanly this applies.

**Comment by cbracken** [comment]
FYI @davidmorgan

**Comment by cbracken** [comment]
I'm going to declare victory here. 3.0.0-nullsafety has been published and the code has been successfully rolled internally.

Once Dart SDK 2.12.0 is out on stable, we'll want to merge the `null_safety` branch to `master` and publish the official 3.0.0 version on pub.
